packages:
  - apps/knowledge/*
  - packages/*
  - tools/*

catalog:
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  eslint: ^9.12.0
  prettier: ^3.3.3
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
