packages:
  - apps/knowledge/*
  - packages/*
  - tools/*

catalog:
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  eslint: ^9.12.0
  prettier: ^3.3.3
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
  mui6:
    "@emotion/cache": ^11.14.0
    "@emotion/react": ^11.14.0
    "@emotion/styled": ^11.14.0
    "@mui/icons-material": ^6.3.1
    "@mui/material": ^6.3.1
    "@mui/material-nextjs": ^6.3.1
